Repository cerner/terra-framework, pull requests merged in 2018-06, with the labels that each got.

#192 Update Jest and other dev dependencies (except eslint)
  package.json
  packages/terra-application-layout/tests/jest/__snapshots__/ApplicationHeader.test.jsx.snap
  packages/terra-application-layout/tests/jest/__snapshots__/ApplicationLayout.test.jsx.snap
  packages/terra-application-layout/tests/jest/__snapshots__/ApplicationMenu.test.jsx.snap
  packages/terra-application-layout/tests/jest/__snapshots__/ApplicationMenuWrapper.test.jsx.snap
  packages/terra-application-layout/tests/jest/__snapshots__/RoutingMenu.test.jsx.snap
  packages/terra-application-layout/tests/jest/__snapshots__/UtilityMenuWrapper.test.jsx.snap
  packages/terra-application-utility/tests/jest/__snapshots__/ApplicationHeaderUtility.test.jsx.snap
  packages/terra-application-utility/tests/jest/__snapshots__/ApplicationMenuUtility.test.jsx.snap
  packages/terra-application-utility/tests/jest/__snapshots__/UtilityButton.test.jsx.snap
  packages/terra-application-utility/tests/jest/__snapshots__/UtilityMenu.test.jsx.snap
  packages/terra-modal-manager/tests/jest/ModalManager.test.jsx
  packages/terra-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
  packages/terra-navigation-layout/tests/jest/__snapshots__/NavigationLayout.test.jsx.snap
  packages/terra-navigation-side-menu/tests/jest/__snapshots__/NavigationSideMenu.test.jsx.snap
Labels: Small, tech-only

#191 add start-static
  package.json
Labels: Small, tech-only

#199 Update babel preset Dependency
  .babelrc
  package.json
Labels: build-tools

#206 Enable new-relic monitoring for terra-framework
  .travis.yml
  package.json
Labels: Small, tech-only

#208 Fixed ariaLabel props in NotificationDialog
  packages/terra-notification-dialog/CHANGELOG.md
  packages/terra-notification-dialog/src/NotificationDialog.jsx
  packages/terra-notification-dialog/src/terra-dev-site/test/notification-dialog/NotificationDialogVariant.test.jsx
Labels: bug, notification-dialog

#212 Implement request animation frame to correct loop limit error.
  packages/terra-application-links/CHANGELOG.md
  packages/terra-application-links/src/tabs/ApplicationTabs.jsx
  packages/terra-hookshot/CHANGELOG.md
  packages/terra-hookshot/src/HookshotContent.jsx
Labels: application-links, bug, hookshot, tech-only

#178 Create Dialog modal
  README.md
  packages/terra-dialog-modal/.npmignore
  packages/terra-dialog-modal/.npmrc
  packages/terra-dialog-modal/CHANGELOG.md
  packages/terra-dialog-modal/LICENSE
  packages/terra-dialog-modal/NOTICE
  packages/terra-dialog-modal/README.md
  packages/terra-dialog-modal/docs/DEPENDENCIES.md
  packages/terra-dialog-modal/docs/README.md
  packages/terra-dialog-modal/package.json
  packages/terra-dialog-modal/src/DialogModal.jsx
  packages/terra-dialog-modal/src/DialogModal.scss
  packages/terra-dialog-modal/src/terra-dev-site/doc/DialogModal.doc.jsx
  packages/terra-dialog-modal/src/terra-dev-site/doc/example/DefaultDialogModal.jsx
  packages/terra-dialog-modal/src/terra-dev-site/doc/example/DialogModalContainer.jsx
  packages/terra-dialog-modal/src/terra-dev-site/doc/example/DialogModalOnModalManager.jsx
  packages/terra-dialog-modal/src/terra-dev-site/doc/example/DialogModalWithCustomHeaderAndCustomFooter.jsx
  packages/terra-dialog-modal/src/terra-dev-site/doc/example/DialogModalWithFocus.jsx
  packages/terra-dialog-modal/src/terra-dev-site/doc/example/DialogModalWithLongText.jsx
  packages/terra-dialog-modal/src/terra-dev-site/doc/example/example-styles.scss
  packages/terra-dialog-modal/src/terra-dev-site/test/dialog-modal/DefaultDialogModal.test.jsx
  packages/terra-dialog-modal/src/terra-dev-site/test/dialog-modal/DialogModalWithCustomHeaderAndCustomFooter.test.jsx
  packages/terra-dialog-modal/src/terra-dev-site/test/dialog-modal/DialogModalWithLongText.test.jsx
  packages/terra-dialog-modal/tests/jest/DialogModal.test.jsx
  packages/terra-dialog-modal/tests/jest/DialogModalExample.jsx
  packages/terra-dialog-modal/tests/jest/__snapshots__/DialogModal.test.jsx.snap
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Default_Dialog_Modal[default].1000x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Default_Dialog_Modal[default].470x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Default_Dialog_Modal[default].838x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Default_Dialog_Modal_with_Themable_Properties[themed].1000x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Default_Dialog_Modal_with_Themable_Properties[themed].470x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Default_Dialog_Modal_with_Themable_Properties[themed].838x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Dialog_Modal_With_Custom_Header_and_Custom_Footer[default].1000x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Dialog_Modal_With_Custom_Header_and_Custom_Footer[default].470x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Dialog_Modal_With_Custom_Header_and_Custom_Footer[default].838x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Dialog_Modal_With_Long_text[default].1000x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Dialog_Modal_With_Long_text[default].470x768.png
  packages/terra-dialog-modal/tests/wdio/__snapshots__/reference/chrome/Dialog_Modal_With_Long_text[default].838x768.png
  packages/terra-dialog-modal/tests/wdio/dialog-modal-spec.js
Labels: dialog-modal, new feature
